version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  gameserver-backend:
    build:
      context: ./GameServer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
  
  client-frontend:
    build:
      context: ./PlayerClient
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gameserver-backend
