version: '3.8'

services:
  gameserver-backend:
    build:
      context: ./GameServer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  
  client-frontend:
    build:
      context: ./PlayerClient
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gameserver-backend
