
# Stage 1: Build stage
FROM maven:3.8.4-openjdk-11 AS build
WORKDIR /app
COPY pom.xml .
COPY ./src ./src
RUN mvn clean package -DskipTests

# Stage 2: Tomcat runtime stage
FROM tomcat:10.1
# WORKDIR /usr/local/tomcat/webapps
# RUN rm -rf ROOT
COPY --from=build /app/target/GameServer-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/gameserver.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
