FROM node:14 AS builder
WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm install
COPY . .
RUN npm run build

FROM httpd:2.4

# Copy built files from the builder stage to Apache's document root
COPY --from=builder /usr/src/app/dist/ /usr/local/apache2/htdocs/

EXPOSE 80
